version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/sonar-ps-plugin"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/sampleProject"
    schedule:
      interval: "daily"
