strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- task: JavaToolInstaller@1
  displayName: 'Set up JDK 17'
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- powershell: |
   if($PSVersionTable.PSVersion.Major -lt 6)
   {
     Install-PackageProvider nuget -Force
   }
   Install-Module -Name PSScriptAnalyzer -RequiredVersion 1.17.1 -Scope "CurrentUser" -Force
  displayName: 'Install PSScriptAnalyzer'

- task: Maven@4
  displayName: 'Maven sonar-ps-plugin/pom.xml'
  inputs:
    mavenPomFile: 'sonar-ps-plugin/pom.xml'
    jdkVersionOption: '1.17'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'build-$(Agent.OS)'    