name: PR Labels Validation

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, labeled, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate_label:
    name: Check labels
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: agilepathway/label-checker@v1.6.65
        with:
          any_of: feature,enhancement,bug,fix,chore,refactor,dependencies,documentation,major,skip-changelog
          repo_token: ${{ secrets.GITHUB_TOKEN }}